version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: rails_react_ecommerce_production
    restart: always

  web:
    build:
      context: .
      args:
        RAILS_ENV: production
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -e production -b 0.0.0.0"
    volumes:
      - ./public:/app/public
      - ./log:/app/log
      - ./storage:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
      RAILS_LOG_TO_STDOUT: 'true'
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: rails_react_ecommerce_production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: always

volumes:
  postgres_data:
